// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebCrawler.Persistence;

#nullable disable

namespace WebCrawler.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230413085845_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebCrawler.Persistence.Entities.CrawledSite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CrawlDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CrawledSites");
                });

            modelBuilder.Entity("WebCrawler.Persistence.Entities.CrawledSiteResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CrawledSiteId")
                        .HasColumnType("int");

                    b.Property<long?>("ResponseTimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UrlFoundLocation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CrawledSiteId");

                    b.ToTable("CrawledSiteResults");
                });

            modelBuilder.Entity("WebCrawler.Persistence.Entities.CrawledSiteResult", b =>
                {
                    b.HasOne("WebCrawler.Persistence.Entities.CrawledSite", "CrawledSite")
                        .WithMany("CrawlResults")
                        .HasForeignKey("CrawledSiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrawledSite");
                });

            modelBuilder.Entity("WebCrawler.Persistence.Entities.CrawledSite", b =>
                {
                    b.Navigation("CrawlResults");
                });
#pragma warning restore 612, 618
        }
    }
}
